### ISSUE TITLE
no line on chart

### ISSUE THREAD

**Issue by galibozek** [blackadderkate/weather-widget-2#102]
After upgrade frameworks to 5.97 (problem around .94/95), the line stopped showing in chart
qt 5.15.5, plasma 5.25.4, arch linux

![Screenshot_20220823_214926](https://user-images.githubusercontent.com/70749001/186252906-71844084-f907-479a-a8c3-9f82d6a27ce9.png)

```
sie 23 21:36:47 plasmashell[1136]: file:///usr/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/config/ConfigAppearance.qml:159: TypeError: Property 'get' of object 1 is not a function
sie 23 21:37:12 plasmashell[1136]: file:///usr/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/config/ConfigAppearance.qml:159: TypeError: Type error


sie 23 21:46:57 plasmashell[1136]: <Unknown File>: temperature0 is undefined. Adding an object with a undefined member does not create a role for it.
sie 23 21:46:57 plasmashell[1136]: <Unknown File>: iconName0 is undefined. Adding an object with a undefined member does not create a role for it.
sie 23 21:46:57 plasmashell[1136]: <Unknown File>: isPast0 is undefined. Adding an object with a undefined member does not create a role for it.
sie 23 21:46:57 plasmashell[1136]: <Unknown File>: temperature1 is undefined. Adding an object with a undefined member does not create a role for it.
sie 23 21:46:57 plasmashell[1136]: <Unknown File>: iconName1 is undefined. Adding an object with a undefined member does not create a role for it.
sie 23 21:46:57 plasmashell[1136]: <Unknown File>: isPast1 is undefined. Adding an object with a undefined member does not create a role for it.
sie 23 21:46:57 plasmashell[1136]: <Unknown File>: temperature2 is undefined. Adding an object with a undefined member does not create a role for it.
sie 23 21:46:57 plasmashell[1136]: <Unknown File>: iconName2 is undefined. Adding an object with a undefined member does not create a role for it.
sie 23 21:46:57 plasmashell[1136]: <Unknown File>: isPast2 is undefined. Adding an object with a undefined member does not create a role for it.
sie 23 21:46:57 plasmashell[1136]: file:///usr/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/Meteogram.qml:450: TypeError: Cannot read property 'clearRect' of undefined
sie 23 21:46:57 plasmashell[1136]: file:///usr/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/Meteogram.qml:504: TypeError: Cannot read property 'clearRect' of undefined
sie 23 21:46:57 plasmashell[1136]: file:///usr/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/Meteogram.qml:477: TypeError: Cannot read property 'clearRect' of undefined
```

**Comment by fkru** [comment]
Version 2.2.2 works fine for current openSUSE Tumbleweed with KDE Plasma 5.25.4, Frameworks 5.97.0, and Qt 5.15.5. Downstream issue?

**Comment by galibozek** [comment]
i use 2.2.4.2 and 2.2.5beta

**Comment by blackadderkate** [comment]
Bit confused about this one. I think the "clearRect" errors are the ones that need to be looked at, but I'm not entirely sure what needs to be fixed...
I'll see if I can find any release notes for Framework 5.97.0 to see if they've changed anything...

**Comment by blackadderkate** [comment]
Do you know how to apply a patch @galibozek ?
I'm on Kubuntu 22.04, with an older Framework, so I'm unable to replicate the bug myself - I'd be interested to know what happens with this patch...

[diff.txt](https://github.com/blackadderkate/weather-widget-2/files/9446434/diff.txt)

**Comment by galibozek** [comment]
I don't see the visual difference, 

[patch-line.txt](https://github.com/blackadderkate/weather-widget-2/files/9447405/patch-line.txt)

**Comment by blackadderkate** [comment]
> I don't see the visual difference,

OK, since I don't have the same Framework version as you I have to try various things to narrow down the issue.

> I can reproduce this suspending laptop without the power cable plugged in. After resume the context variable is null. I think it can be solved by getting the context on every paint.
> 
> ```
>     onPaint: {
>         var ctx = getContext("2d");
>     }
> ```
> 
> The example code always gets the context: https://doc.qt.io/qt-5/qml-qtquick-canvas.html#details

I spotted the same thing in the documentation - I am going to use that syntax in my next patch...

**Comment by blackadderkate** [comment]
@galibozek OK, please can you try this patch instead:
[patch2.txt](https://github.com/blackadderkate/weather-widget-2/files/9485506/patch2.txt)

Don't forget to reverse the old patch first, with -R

And also don't forget that you need to logout and back in again (or kill the plasmashell process and restart it) for the changes to take effect.

**Comment by galibozek** [comment]
patch2 fixed the problem, thanks :)
